### ISSUE TITLE
Do a general refactor now that I'm better at Swift/iOS

### ISSUE THREAD

**Issue by iGman7** [aclissold/the-oakland-post#49]
just found your work!
im newbie but i am amazed on what i have just seen!!!
have read your comment on a previous "issue" and have made changes to the categories myself with your help of course!!

as for the first tab..how can i fetch news from my own rss website like on the sections?
i mean when i go to "BlogsViewController" and enter my rss us and run the app the first tab says "error" and nothing else :(

**Comment by aclissold** [comment]
There's probably quite a few things that might break it because there's Oakland-Post-specific stuff throughout the app. I should probably refactor the code so that changing the RSS feed "just works" anyway! I'm not sure when I'll get around to it though lol.

**Comment by iGman7** [comment]
its a very interesting code and has some quite helpful stuff especially of u that are starting to learn swift :dart:
