### ISSUE TITLE
Swift Compiler Error 

### ISSUE THREAD

**Issue by syedrazanaqvi** [aclissold/the-oakland-post#51]
I am using xcode 6.1 on OSX 10.9.5 but when I am running simulator getting following error

iCarousel.h
Swift Compiler Error 
Expected Identifier or '('

Can you help to resolve it?

**Comment by aclissold** [comment]
This project has been updated to use Swift 1.2 so it will probably only work on Xcode 6.3 or 6.4. Have you tried either of those?
