### ISSUE TITLE
add bitcode for ios 9

### ISSUE THREAD

**Issue by chrisdedow** [aclissold/the-oakland-post#52]

**Comment by aclissold** [comment]
<img width="667" alt="screen shot 2015-10-25 at 7 51 35 pm" src="https://cloud.githubusercontent.com/assets/4397642/10718837/d3261664-7b51-11e5-9c0b-3a84eb2096ed.png">

?

**Comment by chrisdedow** [comment]
One of the parse files needed to be redownloaded since they updated them to
meet apples requirements for having bit code.

**Comment by aclissold** [comment]
Oh! Well I just updated parse to the latest version so that should help, thanks for the info!
