### ISSUE TITLE
Parse service shutdown

### ISSUE THREAD

**Issue by peterkos** [aclissold/the-oakland-post#53]
[https://www.parse.com/migration](https://www.parse.com/migration)

Parse will be shutting down on January 28th, 2017. 
Suggestion: migrate to another database platform?

I'm new to Cocoa/CocoaTouch development, so I'm not sure as to _what_ database platform would be best.

**Comment by aclissold** [comment]
Unfortunately, I'm no longer maintaining this project, so it will remain as-is. Sorry!
